apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marketpulse-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
spec:
  rules:
  - host: marketpulse.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: marketpulse-api-service
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: marketpulse-dashboard-service
            port:
              number: 8501
